export class Car {
    _id: string;
    DateOfPost: String;
    Views: Number;
    Reserved: String;
    Title: String
    Images: [];
    Kilometers: String;
    Price: String;
    // State
    Condition: String;
    PreviousOwners: String;
    InspectionNew: String;
    Warranty: String;
    FullService: String;
    NonSmokingVehicle: String;
    // Performance
    GearingType: String;
    EngineVolume: String;
    DriveChain: String;
    Cylinders: String;
    HorsePower: String;
    Torque: String;
    // Environment
    Fuel: String;
    Consumption: String;
    CO2Emission: String;
    EmissionClass: String;
    EmissionLabel: String;
    // Properties
    Brand: String;
    Model: String;
    FirstRegistration: String;
    BodyColor: String;
    PaintType: String;
    BodyColorOriginal: String;
    InteriorFittings: String;
    InteriorColors: String;
    Body: String;
    NrofDoors: String;
    NrofSeats: String;
    ModelCode: String;
    CountryVersion: String;
    // Equipment
    ComfortAndConvenience: [];
    EntertainmentAndMedia: [];
    Extras: [];
    SafetyAndSecurity: [];
    // Description
    Description: String;
}